/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export default function Model({ ...props }) {
    const group = useRef()
    useFrame((state, delta) => {
        // console.log(group.current.position.x)
        if (group.current.position.x >= 0.5) {
            group.current.position.x -= 0.7
            group.current.position.y -= 0.25
        }
    })
    const { nodes, materials } = useGLTF("/ambulance.gltf")
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.ambulance_1.geometry}
                    material={materials["paintWhite.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_2.geometry}
                    material={materials["paintRed.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_3.geometry}
                    material={materials["plastic.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_4.geometry}
                    material={materials["_defaultMat.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_5.geometry}
                    material={materials["lightFront.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_6.geometry}
                    material={materials["window.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_7.geometry}
                    material={materials["lightBlue.001"]}
                />
                <mesh
                    geometry={nodes.ambulance_8.geometry}
                    material={materials["carTire.001"]}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/ambulance.gltf")
