/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export default function Model({ ...props }) {
    const group = useRef()
    useFrame((state, delta) => {
        // console.log(group.current.position.x)
        if (group.current.position.x >= 0.5) {
            group.current.position.x -= 0.7

            group.current.position.y -= 0.1
            group.current.rotation.y += 0.01

            group.current.position.z += 0.01
        }
    })
    const { nodes, materials } = useGLTF("/electric.gltf")
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.hatchbackSports_1.geometry}
                    material={materials["plastic.006"]}
                />
                <mesh
                    geometry={nodes.hatchbackSports_2.geometry}
                    material={materials["paintGreen.003"]}
                />
                <mesh
                    geometry={nodes.hatchbackSports_3.geometry}
                    material={materials["lightFront.006"]}
                />
                <mesh
                    geometry={nodes.hatchbackSports_4.geometry}
                    material={materials["_defaultMat.006"]}
                />
                <mesh
                    geometry={nodes.hatchbackSports_5.geometry}
                    material={materials["window.006"]}
                />
                <mesh
                    geometry={nodes.hatchbackSports_6.geometry}
                    material={materials["lightBack.004"]}
                />
                <mesh
                    geometry={nodes.hatchbackSports_7.geometry}
                    material={materials["carTire.006"]}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/electric.gltf")
