/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export default function Model({ ...props }) {
    const group = useRef()
    useFrame((state, delta) => {
        // console.log(group.current.position.x)
        if (group.current.position.x >= 0.5) {
            group.current.position.x -= 0.7

            group.current.position.y -= 0.1
            group.current.rotation.y += 0.02
        }
    })
    const { nodes, materials } = useGLTF("/pick-up.gltf")
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.truckFlat_1.geometry}
                    material={materials["plastic.018"]}
                />
                <mesh
                    geometry={nodes.truckFlat_2.geometry}
                    material={materials["window.018"]}
                />
                <mesh
                    geometry={nodes.truckFlat_3.geometry}
                    material={materials["lightBack.012"]}
                />
                <mesh
                    geometry={nodes.truckFlat_4.geometry}
                    material={materials["paintWhite.006"]}
                />
                <mesh
                    geometry={nodes.truckFlat_5.geometry}
                    material={materials["lightFront.016"]}
                />
                <mesh
                    geometry={nodes.truckFlat_6.geometry}
                    material={materials["_defaultMat.018"]}
                />
                <mesh
                    geometry={nodes.truckFlat_7.geometry}
                    material={materials["carTire.018"]}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/pick-up.gltf")
