/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF("/sedan-sport.gltf")
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.sedanSports_1.geometry}
                    material={materials["plastic.011"]}
                />
                <mesh
                    geometry={nodes.sedanSports_2.geometry}
                    material={materials["paintRed.006"]}
                />
                <mesh
                    geometry={nodes.sedanSports_3.geometry}
                    material={materials["_defaultMat.011"]}
                />
                <mesh
                    geometry={nodes.sedanSports_4.geometry}
                    material={materials["window.011"]}
                />
                <mesh
                    geometry={nodes.sedanSports_5.geometry}
                    material={materials["lightBack.007"]}
                />
                <mesh
                    geometry={nodes.sedanSports_6.geometry}
                    material={materials["lightFront.009"]}
                />
                <mesh
                    geometry={nodes.sedanSports_7.geometry}
                    material={materials["carTire.011"]}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/sedan-sport.gltf")
