/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF("/sedan.gltf")
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.sedan_1.geometry}
                    material={materials["plastic.010"]}
                />
                <mesh
                    geometry={nodes.sedan_2.geometry}
                    material={materials["paintRed.005"]}
                />
                <mesh
                    geometry={nodes.sedan_3.geometry}
                    material={materials["lightFront.008"]}
                />
                <mesh
                    geometry={nodes.sedan_4.geometry}
                    material={materials["_defaultMat.010"]}
                />
                <mesh
                    geometry={nodes.sedan_5.geometry}
                    material={materials["window.010"]}
                />
                <mesh
                    geometry={nodes.sedan_6.geometry}
                    material={materials["lightBack.006"]}
                />
                <mesh
                    geometry={nodes.sedan_7.geometry}
                    material={materials["carTire.010"]}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/sedan.gltf")
