/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF("/van.gltf")
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, 0.2, -0.1]}>
                <mesh
                    geometry={nodes.Mesh_body019.geometry}
                    material={materials["plastic.019"]}
                />
                <mesh
                    geometry={nodes.Mesh_body019_1.geometry}
                    material={materials["paintBlue.002"]}
                />
                <mesh
                    geometry={nodes.Mesh_body019_2.geometry}
                    material={materials["lightFront.017"]}
                />
                <mesh
                    geometry={nodes.Mesh_body019_3.geometry}
                    material={materials["_defaultMat.019"]}
                />
                <mesh
                    geometry={nodes.Mesh_body019_4.geometry}
                    material={materials["lightBack.014"]}
                />
                <mesh
                    geometry={nodes.Mesh_body019_5.geometry}
                    material={materials["window.019"]}
                />
            </group>
            <group
                position={[-0.35, 0.3, 0.76]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
            >
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016.geometry}
                    material={materials["carTire.019"]}
                />
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016_1.geometry}
                    material={materials["_defaultMat.019"]}
                />
            </group>
            <group position={[0.35, 0.3, 0.76]}>
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016.geometry}
                    material={materials["carTire.019"]}
                />
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016_1.geometry}
                    material={materials["_defaultMat.019"]}
                />
            </group>
            <group
                position={[-0.35, 0.3, -0.76]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
            >
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016.geometry}
                    material={materials["carTire.019"]}
                />
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016_1.geometry}
                    material={materials["_defaultMat.019"]}
                />
            </group>
            <group position={[0.35, 0.3, -0.76]}>
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016.geometry}
                    material={materials["carTire.019"]}
                />
                <mesh
                    geometry={nodes.Mesh_wheel_frontLeft016_1.geometry}
                    material={materials["_defaultMat.019"]}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/van.gltf")
